%% level1MonochromaticTest.m
%
% LEVEL 1 of the Forward-Model-to-SSI validation ladder: does SSI recover
% a known incident frequency from a genuine, spatially-distributed
% hydroelastic response (multiple real sensor locations on the validated
% Forward Model), rather than from a hand-built oscillator?
%
% IMPORTANT INTERPRETIVE NOTE, kept explicit rather than assumed:
% evaluateSpectralDeflection produces a FORCED STEADY-STATE response to
% an imposed incident wave, not a free-vibration record. The claim being
% tested is precise: this particular deterministic output SEQUENCE (not
% the underlying physical system, which may be arbitrarily complex)
% admits an exact minimal realization with unit-circle discrete-time
% eigenvalues exp(+-i*omega*dt), hence zeta EXACTLY 0 for the true
% underlying tone. A clean recovery here confirms SSI can extract a known
% frequency from real spatial floe physics -- it does NOT confirm omega
% is a natural hydroelastic mode of the floe.

thisDir = fileparts(mfilename('fullpath'));
addpath(fullfile(thisDir, '..'));
addpath(fullfile(thisDir, '..', '..', 'Forward Model'));
addpath(fullfile(thisDir, '..', '..', 'Forward Model', 'Animation'));
addpath(fullfile(thisDir, '..', '..', 'Forward Model', 'JONSWAP'));
clear all, close all, clc

%% Build a near-single-frequency Forward Model scenario (known omega exactly)
Hs = 0.1; w0 = 5.5; gammaJONSWAP = 3.3;
wMin = 5.49; wMax = 5.51; numBins = 1;

H = 1.88; beta = 4.6985e-5; gamma = 1.4548e-3; R = 0.3830; nu = 0.3;
M = 50; P = 10; N = 10;

specData = precomputeSpectralData(Hs, w0, gammaJONSWAP, wMin, wMax, numBins, ...
    H, beta, gamma, R, nu, M, P, N);
omega_true = specData.omega(1);

% Confirm the spectral preprocessing actually produced the intended
% frequency -> w0 is a REQUEST, specData.omega(1) is what actually got
% generated; these need not be identical in general (bin midpoint vs.
% requested peak), and this assumption stops being trivial once Level 2
% introduces multiple bins.
assert(abs(omega_true - w0) < 1e-10, ...
    'Unexpected incident frequency generated by spectral preprocessing: got %.8f, requested %.8f.', ...
    omega_true, w0);
fprintf('True incident angular frequency: %.6f rad/s (confirmed matches requested w0)\n', omega_true);

%% 4 sensor locations, matching Robyn's suggested count
sensorLocations = [0,      0;
                   0.5*R,  0;
                   0.9*R,  0;
                   0.9*R,  pi];
nSensors = size(sensorLocations,1);

%% Sample finely relative to the period, long enough for good resolution
T_period = 2*pi/omega_true;
dt = 0.02;
tVec = 0:dt:60;

fprintf('Sampling: dt=%.3fs, period=%.4fs (%.0f samples/period), total %.1fs (%.1f periods)\n', ...
    dt, T_period, T_period/dt, tVec(end), tVec(end)/T_period);

y = syntheticSensorData(specData, sensorLocations, tVec);

%% Run the full, already-validated SSI chain
i = 30; nMax = 10;
[Yp_ref, Yf, ~] = buildHankelMatrix(y, i);
P_proj = hankelProjection(Yp_ref, Yf);
results = sweepModelOrders(P_proj, nSensors, dt, nMax);

matches = cell(nMax,1);
for n = 2:nMax
    matches{n} = classifyPoleStability(results(n-1), results(n), 0.01, 0.05, 0.99);
end
branches = buildModalBranches(results, matches);
persistence = computeBranchPersistence(branches, 3, 2);

%% Find the persistent branch nearest the true frequency
fprintf('\n=== Searching for a persistent branch near omega_true ===\n');
foundBranch = 0;
for b = 1:length(branches)
    if any(abs(branches(b).frequency - omega_true)/omega_true < 0.01) && persistence(b).isPersistent
        foundBranch = b;
        break;
    end
end

assert(foundBranch > 0, 'Level 1 FAILED: no persistent branch found near the true incident frequency.');
fprintf('PASS: persistent branch found (branch %d, spans orders [%d,%d])\n', ...
    foundBranch, branches(foundBranch).order(1), branches(foundBranch).order(end));

%% Report frequency and damping across EVERY order on the branch, not just
% the lowest -- a stable value across order is more convincing evidence
% than a single point, and shows the stabilization behaviour itself
fprintf('\n=== Frequency and damping across all orders on this branch ===\n');
fprintf('%6s %14s %14s %14s\n', 'Order', 'Frequency', 'RelError', 'Zeta');
relErrors = zeros(size(branches(foundBranch).order));
for k = 1:length(branches(foundBranch).order)
    om = branches(foundBranch).frequency(k);
    ze = branches(foundBranch).damping(k);
    relErrors(k) = abs(om - omega_true)/omega_true;
    fprintf('%6d %14.8f %14.3e %14.3e\n', branches(foundBranch).order(k), om, relErrors(k), ze);
end

%% Two-tier assertion: strict numerical regression vs. scientific criterion
maxRelError = max(relErrors);
fprintf('\nMax relative frequency error across all orders on branch: %.3e\n', maxRelError);

assert(maxRelError < 1e-2, ...
    'Level 1 FAILED (scientific criterion): frequency error exceeds 1%% at some order on the branch.');
fprintf('PASS (scientific criterion, <1%%): SSI recovers the correct frequency at every order on this branch.\n');

if maxRelError < 1e-4
    fprintf('PASS (strict numerical regression, <1e-4): this specific deterministic setup reproduces\n');
    fprintf('  to near machine precision -- treat 1e-4 as a regression benchmark for THIS test config,\n');
    fprintf('  not as the general definition of correct SSI behaviour.\n');
else
    fprintf('NOTE: strict 1e-4 regression benchmark not met (error=%.3e) -- worth investigating why,\n', maxRelError);
    fprintf('  though the looser scientific criterion above still passed.\n');
end

finalZeta = branches(foundBranch).damping(end);
fprintf('\nFinal identified zeta = %.6e (expected near-zero for a forced tone -- reported for\n', finalZeta);
fprintf('inspection; a value appreciably above numerical noise floor would itself be worth\n');
fprintf('investigating, e.g. in syntheticSensorData or the extraction chain).\n');

fprintf('\nThis confirms SSI can extract the known frequency from real spatial floe physics --\n');
fprintf('it does NOT (and is not claimed to) confirm omega is a natural hydroelastic mode.\n');

%% Qualitative logging (not yet a formal check): compare the SSI mode
% shape at the branch's first order against the KNOWN forward-model
% spatial response at the same sensor locations. Formal MAC comparison
% is Level 2's job; this is a first look, logged for reference.
fprintf('\n=== Qualitative mode-shape comparison (informal, Level 2 will formalise this) ===\n');
firstOrder = branches(foundBranch).order(1);
[~, colIdx] = min(abs(results(firstOrder).frequency - branches(foundBranch).frequency(1)));
ssiShapeVec = results(firstOrder).modeShapes(:, colIdx);

knownShapeVec = zeros(nSensors,1);
for s = 1:nSensors
    knownShapeVec(s) = evaluateDeflection(specData.binData{1}, sensorLocations(s,1), sensorLocations(s,2));
end

fprintf('SSI-identified shape (order %d):\n', firstOrder);
disp(ssiShapeVec);
fprintf('Known Forward Model spatial response at same sensors:\n');
disp(knownShapeVec);
fprintf('(Both should show the same RELATIVE pattern across sensors, up to an arbitrary\n');
fprintf(' complex scale factor -- exact numerical comparison via MAC is Level 2''s job.)\n');