function cfg = defineStudyScenarios()
%DEFINESTUDYSCENARIOS  Pre-registered configuration of the final experiment programme.
%   cfg = defineStudyScenarios()
%
%   WHAT WILL BE TESTED, fixed before any sweep is run (SHARC_Experiment_Programme.tex, rev. 3).
%   This file is data: scenario lists, sweep grids, admissibility rules and class thresholds.
%   It runs no EMM solve, Fisher calculation, optimisation or plot. The only arithmetic is the
%   deterministic conversion of finite-depth physical floes to the EMM's scaling (same formulas
%   as screenFloeRegime.m), so every study reads identical (beta, gamma, R) values.
%   Deep-water (MIZ) cases are stored physically; their EMM scaling needs the dispersion
%   relation and is produced by screenFloeRegime.m in the study script.
%
%   Division of labour:
%     defineStudyScenarios.m  what is tested (this file)
%     evaluateScenario.m      how one scenario is evaluated
%     run<Study>.m            loops, optimisation, outputs
%
%   CHANGE CONTROL: after the pre-registration date below, any change is recorded in
%   cfg.meta.changes with a date and reason; never edit a value silently.
%
%   EMM SCALING (from the Forward Model, confirmed in computeSensorFRF.m and screenFloeRegime.m)
%     length scale = water depth H;  alpha = H omega^2 / g
%     beta  = D / (rhoW g H^4) = (l_f / H)^4,   D = E h^3 / (12 (1 - nu^2))
%     gamma = draught / H = rhoI h / (rhoW H)
%     R     = Rphys / H;   sensor radius r = rphys / H
%
% Lives in Inverse Mapping/Parameter Inversion/Design and Robustness/.

%% ---- Metadata ---------------------------------------------------------------------------------
cfg.meta.created = '2026-09-30';
cfg.meta.version = '1.0';
cfg.meta.status = 'PRE-REGISTERED';
cfg.meta.programme = 'SHARC_Experiment_Programme.tex rev. 3';
cfg.meta.changes = struct('date', {}, 'field', {}, 'reason', {});
cfg.meta.changes(end + 1) = struct('date', '2026-10-01', 'field', 'E1.tolD (added)', 'reason', ...
    ['AMENDMENT, not pre-registered. The pre-registration fixed the d_W targets (0.26, 0.91, 3.68) but no ' ...
    'acceptance tolerance. After the first analytic comparison a 10% tolerance was introduced; it reflects the ' ...
    'sampling uncertainty of the 200-realisation Monte Carlo covariance and its inverse. The observed analytic ' ...
    'values are 6-7% below the Monte Carlo-derived targets.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-01', 'field', 'R4.noiseCases, headlineNoise, toleranceSearch, toleranceN (added)', ...
    'reason', ['CLARIFICATION, no value changed. These choices were made in runR4GammaTolerance before it was ' ...
    'run (all noise cases, headline = cfg.noise.default, tolerance search eps in [-0.30, 0.30] on 1201 points). ' ...
    'They are moved here so the configuration alone records what R4 tested.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-02', 'field', 'D2.headlineNoise (added)', 'reason', ...
    ['CLARIFICATION, no value changed. D2 reported its headline case as cfg.noise.default (lsm6dsv16x); ' ...
    'it is fixed here, as for R4, so a later change of the default cannot change D2.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-02', 'field', 'R3.headlineNoise, toleranceSearch, toleranceN (added)', ...
    'reason', ['CLARIFICATION, no value changed. Fixed before the production R3 run, as for R4: headline = ' ...
    'lsm6dsv16x, tolerances searched for eps in [-1, 0.5] (the pre-registered eps range) on 1501 points.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-02', 'field', 'A1.mizEvaluation (added)', 'reason', ...
    ['AMENDMENT before any A1 run. The pre-registration fixed the MIZ period band (6-12.5 s) and the effective ' ...
    'depth rule but no sea state, record or noise for the MIZ cases, and the frozen engine works in basin units. ' ...
    'The EMM sees only alpha, beta, gamma, R, so MIZ cases are evaluated Froude-scaled to the basin: the band maps ' ...
    'through alpha = H_eff omega^2 / g to basin omega and is cut to cfg.band.basin; sea, record and noise are the ' ...
    'basin ones in scaled units. The equivalent full-scale experiment is reported with each result.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-02', 'field', 'A1.maxTruncationBiasDistance (added)', 'reason', ...
    ['AMENDMENT before any A1 run. The programme requires a truncation check per A1 scenario but fixed no ' ...
    'threshold. The node-grid threshold is reused: the [70 15 15] minus [50 10 10] feature difference, projected ' ...
    'with the scenario''s own F, must give d < 0.1, otherwise the scenario is reported as Model check failed.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-02', 'field', 'A1.truncationGate (added; replaces the truncation use of A1.maxTruncationBiasDistance)', ...
    'reason', ['AMENDMENT before the A1 batch, made AFTER the p0 pre-flight result (testA1 check 10 and ' ...
    'diagnoseTruncationP0, 2 Oct 19:07). At p0 the projected feature bias of [50 10 10] against [70 15 15] is d = 0.57 ' ...
    'and of [70 15 15] against [90 20 20] d = 0.25 (the vertical-mode truncation M dominates: M alone 0.54, P 0.14, ' ...
    'N 0.0003; concentrated above 7 rad/s), while sigma, ' ...
    'd_W, kappa and the class change by less than 0.05%. The feature-bias d measures the error of inverting REAL ' ...
    'data with a truncated model (a V1 question); A1 needs to know whether its METRICS are converged. The A1 ' ...
    'truncation gate is therefore metric convergence: a full evaluation at [70 15 15] must give sigma within 1% ' ...
    'relative, d_W within 0.02 absolute and the same class. The feature bias is still computed and reported.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-02', 'field', 'A1.passNuToEMM, A1.modelCheckClass (added)', 'reason', ...
    ['CLARIFICATION, no value changed. The physical nu (0.40 for polypropylene) is passed to the EMM, whose free-edge ' ...
    'conditions depend on nu as well as on D (default 0.30 otherwise). A scenario failing a forward-model check is ' ...
    'labelled Model check failed, separately from the inverse class, which is still recorded.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-03', 'field', 'R2.normalisationBand, bimodalFractionOf, adequacyRule, m1Candidates, m1Rule (added)', ...
    'reason', ['CLARIFICATION before the R2 run, no value changed. (i) The programme text says "at fixed Hs"; the ' ...
    'frozen config says fixed in-band elevation variance, which is what R2 implements: every sea has the reference ' ...
    'sea''s elevation variance inside the retained band cfg.band.basin, so moving omega_p does not change the in-band ' ...
    'signal level (R1 covers the level). (ii) The bimodal energy fractions 0.4/0.6 are fractions of that in-band ' ...
    'variance. (iii) "L = 2048 adequate" for a sea means Identifiable at L = 2048 under the frozen class thresholds. ' ...
    '(iv) The R2 case handed to M1 ("narrowest or bimodal sea") is fixed now: among the gamma_J = 7 seas and the ' ...
    'bimodal sea, the one with the largest max(s_max / 0.01, d_W / 0.5, kappa / 1e8) at L = 2048.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-03', 'field', 'M1.rules{1}', 'reason', ...
    ['AMENDMENT after D1, before M1. The rule was "D1 optimum at n_s = 3 (fewest sensors that should work)"; D1 ' ...
    'recommends n_s = 2 (s6 + reference s18), so by the rule''s own rationale the M1 case is the n_s = 2 optimum. ' ...
    'Rule 3 now points to the pre-fixed R2 selection rule.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-04', 'field', ['V1 depth alpha-range clarification; ' ...
    'V1.toleranceTol replaced by toleranceTolDecades, toleranceFloorFraction (PRE-RUN CORRECTION)'], 'reason', ...
    ['PRE-RUN CORRECTION from testV1ModelMismatch, before any V1 production run. (i) The earlier 13.87 estimate ' ...
    'used the continuous 8.301 rad/s band edge; the highest retained Welch bin gives alpha = 13.807 at +5% depth, ' ...
    'inside the validated 13.85. The fixed synthesis support still reaches alpha = 14.542, so the extrapolation ' ...
    'flag and the support caveat are unchanged. (ii) Tolerance resolution: the tester''s radial +1 cm case gives ' ...
    'd_sys = 98, so with d_sys roughly proportional to the error the d_sys = 0.5 and 1 crossings lie near 0.05 to ' ...
    '0.1 mm, below the absolute bisection tolerance of 0.2 mm, which could not resolve them. The bisection therefore ' ...
    'runs in log10 of the error magnitude to 0.005 decade (1.2% relative) for both axes; when the crossing lies ' ...
    'between 0 and the first registered point, the lower bracket is 1e-4 of that point (if the criterion is already ' ...
    'exceeded there, the tolerance is reported as below it). What is measured, the thresholds and the registered ' ...
    'range are unchanged; only the precision with which a crossing is located.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-04', 'field', 'V1.truncationTruth, truncationTruthSelected', ...
    'reason', ['RESULT OF THE PRE-REGISTERED STAGE-0 DIAGNOSTIC truncationLadder_20261004_113129. The first p0 ' ...
    'consecutive M step below d = 0.1 was [110 20 20] -> [130 20 20], d = 0.0790 ([90 20 20] -> [110 20 20]: ' ...
    'd = 0.1248), so [130 20 20] is the V1 truth truncation. The P check [130 20 20] -> [130 30 20] gave d = 0.0500 ' ...
    'and the same M step at the three large-kR A1 floes d = [0.0623 0.0573 0.0686], all below 0.1, so no ' ...
    'follow-up amendment is needed and the large-kR V1a results are not lower bounds.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-04', 'field', ['V1.truncationTruthSelected, radialErrorAppliesTo, ' ...
    'depthModel, toleranceThresholds, toleranceTol, nonlinear (added)'], 'reason', ['CLARIFICATION before the V1 run, ' ...
    'no registered value changed. (i) The systematic bias is Welch expectation minus Welch expectation, ' ...
    'b_sys = f_W(truth) - f_W(nominal), projected with the nominal J, Sigma, F; d_tot adds dtheta_W and ' ...
    'dtheta_sys as vectors (programme rule). (ii) Depth error is physical: H_true = H0 (1 + eps) with the floe, the ' ...
    'sensors'' physical positions and the physical-frequency sea fixed, so beta ~ H^-4, gamma ~ H^-1, R ~ H^-1, ' ...
    'r_i ~ H^-1 and alpha = H omega^2 / g change together. The synthesis band and taper are held at the NOMINAL ' ...
    'physical band, so b_sys contains depth-model mismatch and not a change of excitation. At +5% depth the ' ...
    'highest retained Welch bin stays inside the validated alpha window (13.81 against 13.85; corrected, see the ' ...
    'pre-run correction entry), while the fixed synthesis support extends to alpha = 14.54. The support ' ...
    'extrapolation is reported per case (alpha min/max, retained and support) as a validity caveat and is not ' ...
    'used to alter the forcing. (iii) Radial error: one common signed shift of every ' ...
    'sensor with r > 0, angles unchanged. (iv) Tolerances: first crossings of d_sys = 0.5 and 1 and |dbeta/beta| = 1% ' ...
    'per side, bracketed by the registered points (and 0), refined by bisection (resolution: see the pre-run ' ...
    'correction entry); if not crossed, reported as beyond ' ...
    'the registered range, which is not extended. (v) One nonlinear check, diagnostic only: after all registered ' ...
    'cases are evaluated, the case with the largest analytic d_sys is inverted with the unchanged G3 solver from ' ...
    'theta_true on its noiseless Welch features, and compared with the TOTAL linear prediction theta_true + ' ...
    'dtheta_W + dtheta_sys (gap per sigma and d; 0.2 sigma as a reference line, not a gate). (vi) The runner ' ...
    'refuses to start until V1.truncationTruthSelected is true (stage 0 logged) and the tree is clean.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-04', 'field', ['V1.truncationLadderM, truncationLadderPN, ' ...
    'truncationConvergedD, truncationFloes, truncationCheckP (added)'], 'reason', ['CLARIFICATION before V1 stage 0, ' ...
    'no study value changed. The rule of programme rev. 5 (extend the vertical-mode truncation M until one consecutive ' ...
    'step changes the features by d < 0.1) is fixed as: M = 90, 110, ..., 210 with P = N = 20 (A1: M dominates, ' ...
    'N negligible), d measured with the production ruler (F, J, Sigma at [50 10 10]) on exact features, selection at ' ...
    'p0; the higher member of the first passing pair becomes V1.truncationTruth (logged separately when known). ' ...
    'Reported but not used for the selection: the same last step at the three large-kR A1 floes (R = 2 R0), and a P ' ...
    'check [M* 20 20] -> [M* 30 20] at p0. If no step passes by M = 210, V1a reports the best available level as not ' ...
    'converged (a lower bound on the truncation bias); the range is not extended without a logged change.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-03', 'field', ['M1.caseNames, D1, A1scenario, R2sea, R1noiseCase, ' ...
    'seedBase, seedStride, nonlinearRecord, solver, sigmaSource, borderline, checkpointEvery, sourceRelTol, requireCleanTree (added)'], ...
    'reason', ['CLARIFICATION before the M1 run, no acceptance value changed. (i) The four cases are the ones resolved ' ...
    'by the rules after D1, A1 and R2: D1 n_s = 2 optimum s6 + reference s18 (LSM6DSV16X, 0.10 m spacing); ' ...
    'miz_R25_h1 exactly as A1 built it (Froude-scaled, its band, nu, Level 2C at its true R); wp3.5_gJ7 exactly as R2 ' ...
    'built it (fixed in-band variance, L = 2048); p0 with Level 2C and reference s26 at LSM6DSV16X and the R1/E1 sea. ' ...
    'Each must reproduce its source study''s sigma and d_W (relative 1e-6) before any record is generated. ' ...
    '(ii) M1 tests the ANALYTIC (E1) predictions: the linearised estimate and q use the engine''s J, Sigma_k and F ' ...
    'on its accepted bins (G3 used a 200-record Monte Carlo Sigma; that is what E1 replaced). q and coverage follow ' ...
    'G3a exactly: q = dtheta'' F dtheta with dtheta = theta_hat - theta_true (centred on the truth, not on the Welch ' ...
    'bias; E[q] = 2 + d_W^2), chi2(2) quantiles at 68.27 and 95%. The nonlinear-vs-linearised criterion follows G3.1 ' ...
    'exactly: |theta_NL - theta_lin| / sigma < 0.2 per component, on the same record; a run must also converge. ' ...
    '(iii) Records come from synthesiseTwinRecords on the engine''s own field twin (the same node grid as the ' ...
    'analytic prediction: node-grid mismatch is removed as a confound, so M1 isolates the finite-record estimator and ' ...
    'the analytic Fisher/bias prediction; model discretisation belongs to A1 and V1), with the estimator, solver and solver settings of G3 unchanged (g3EstimatorCore, verbatim ' ...
    'copy, checked by the tester). Seeds: seed = seedBase + seedStride * caseIndex + record (noise seed + 1e6, the ' ...
    'synthesiseTwinRecords default). Nonlinear inversions use record 1 and start at beta x (1 + offset), R at the ' ...
    'truth. (iv) "Borderline" (extend 100 -> 200 records, records 101-200 added, once): the 1-standard-error ' ...
    'interval of emp/pred (se = r / sqrt(2(n - 1))) or of the 95% coverage (binomial se, p(1-p) floored at ' ...
    '0.95 x 0.05) contains an acceptance limit. The mean offset against the Welch-expected bias is reported as a ' ...
    'diagnostic (G3.3 rule, within 3 standard errors), not an acceptance criterion. (v) A record with a rejected ' ...
    'bin that the analytic mask accepts is counted and estimated without that bin. (vi) The runner refuses to start ' ...
    'with uncommitted .m files (the R1 provenance note), unless explicitly overridden.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-03', 'field', 'R1.boundaryRule, refineTolDecades, equivalentHsSensor (added)', ...
    'reason', ['CLARIFICATION before the R1 run, no value changed. The class need not improve monotonically as the noise ' ...
    'falls: F grows while the Welch feature bias does not, so d_W rises at the quiet end (D2: datasheet grade Marginal at ' ...
    '109 min). R1 therefore reports ALL class transitions on the pre-registered S_nn interval: the 41-point sweep ' ...
    'brackets them, each is refined in log10(S_nn) on the criterion that changes (s_max, d_W or kappa), and the binding ' ...
    'criterion is reported. Each boundary is also given as an equivalent Hs for the LSM6DSV16X (SNR ~ Hs^2 / S_nn).']);

cfg.meta.changes(end + 1) = struct('date', '2026-10-05', 'field', ['V2.primaryHeadingDeg, energyConvention, ' ...
    'operatingPoint, thresholds, toleranceTolDecades, toleranceFloorFraction, coherence, mirrorCheckDeg, nonlinear, ' ...
    'requireCleanTree (added)'], 'reason', ['CLARIFICATION before any V2 result; the registered angles [15 30 60 90] deg ' ...
    'and second-component fractions [0.05 0.10 0.25 0.50] are unchanged. (i) Forcing: two independent components from ' ...
    'the same JONSWAP shape, primary at 0 deg (the EMM incidence, the Level 2C/D1 axis), secondary at +phi; total ' ...
    'incident energy fixed (S_u1 = (1 - f2) S_u, S_u2 = f2 S_u) so directionality is not confounded with SNR; a ' ...
    'component from heading phi is the nominal field at the sensors rotated by -phi (circular floe). Spectral matrix ' ...
    'S = sum_c f_c H_c H_c^H S_u (Welch-smoothed with the engine kernel) + diag(S_nn), directionalSpectralMatrix.m, ' ...
    'shared with D3. (ii) Bias as V1: b_dir = f_W(directional) - f_W(single), both Welch expectations through the same ' ...
    'function, projected with the NOMINAL J, Sigma, F on the nominal accepted bins; d_tot from the vector sum with ' ...
    'dth_W; class. (iii) Tolerances in f2 per phi as V1 (first crossing of d_sys = 0.5, 1 and |dbeta/beta| = 1%, ' ...
    'bisection in log10 f2 to 0.005 decade, lower bracket 1e-4 of the first registered fraction, not extrapolated ' ...
    'beyond 0.5). (iv) Coherence detectability: expected MSC of each transmissibility pair under the single-direction ' ...
    '(noisy) model and under the directional sea; Fisher z = atanh(|gamma|) with variance 1/(2 (N_eff - 1)) per bin; ' ...
    'the standardised mean drop over the accepted bins D_j = mean(z_single - z_dir) sqrt(2 (N_eff - 1) n_bins) ' ...
    '(bins treated as independent, the every-second-bin grid); detectable when max_j D_j >= z(1 - 0.05/m) + z(0.80) ' ...
    '(one-sided 5% test, Bonferroni over the m pairs, 80% power); f_detect is its first crossing in f2, found as the ' ...
    'tolerances. The coherence baseline is the model prediction at the true parameters (a limitation). (v) Nonlinear ' ...
    'diagnostic (as V1, G3 solver from theta_true on the noiseless Welch features) at the d_sys = 1 crossing of the ' ...
    'most sensitive angle (smallest crossing f2), where the tolerance conclusions are drawn; if no angle crosses, the ' ...
    'registered case with d_sys closest to 1 in log10. (vi) Operating point p0, Level 2C, reference ' ...
    's26, LSM6DSV16X, setting F, [50 10 10] (the E1 default). (vii) The runner refuses to start with uncommitted code.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-05', 'field', ['V2.coherence.nullRecords, nullSeedBase, ' ...
    'nullRecordsTest, V2.linearityF2 (added); crossing status'], 'reason', ['AMENDMENT before any V2 run (tester not yet ' ...
    'run), after review; registered angles, fractions and thresholds unchanged. (i) The coherence statistic no longer ' ...
    'assumes independent bins: D_j = mean_k(z_single - z_dir) / sd_j with sd_j the Monte Carlo standard deviation of ' ...
    'the bin-mean Fisher z of the real estimator (extractTransmissibility coherence on 400 single-direction twin records, ' ...
    'nominal sea and noise, seeds 800001...) about its analytic expectation; the analytic 1/sqrt(2 nDof n_bins) and the ' ...
    'effective number of independent bins are reported. z(1 - 0.05/m) + z(0.80) is the 80%-power detectability ' ...
    'threshold (the 5% rejection threshold is z(1 - 0.05/m)). (ii) Crossing status exact | below_floor | not_crossed: ' ...
    'a criterion already met at the bisection floor (1e-4 of the first registered f2) is below_floor, not a crossing; ' ...
    'if detection and d_sys = 0.5 are both below the floor the ordering is reported as unresolved. The crossings are ' ...
    'boundary refinements inside the bracket between the exact f2 = 0 baseline and the first registered point. (iii) ' ...
    'Local-regime check: d_sys / f2 at f2 = 2.5e-4, 5e-4, 1e-3 per angle (constant if b_dir ~ f2), reported. (iv) The ' ...
    'class is under the nominal uncertainty ruler (nominal sigma, directional total bias); sigma under the directional ' ...
    'sea is a diagnostic. (v) spreadWeights uses the wrapped angular difference (D3).']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-05', 'field', 'D3.* (added)', 'reason', ['CLARIFICATION before ' ...
    'any D3 run, implementing programme rev. 4 (no registered criterion changed). (i) Headings: see the AMENDMENT ' ...
    'entry (7.5 + 15k deg); heading 0 is still evaluated (known heading) for the D1 gate and the D1 efficiency. (ii) ' ...
    'D3a: theta = [ln beta, ln R, psi], dT/dpsi by central differences of the rotated field (+-0.5 deg; the tester ' ...
    'requires +-0.25 deg to agree within 0.1% in A); the (beta, R) ' ...
    'uncertainty is the Schur complement F_eff = F_tt - F_tp F_pp^-1 F_pt per heading (F_pp = 0 exactly: F_eff = F_tt); ' ...
    'A = tr(F_eff^-1), the Welch bias from the 3-parameter projection, class from sigma, d_W and cond(F_eff); best ' ...
    'reference per heading (the reference is a processing choice). Mean A and worst-case A over the 24 headings, never ' ...
    'A of a heading-averaged F. Headings are evaluated through the eight-fold grid symmetry: heading 45k + delta of ' ...
    'layout L equals heading delta of L rotated by -45k deg, so three rotated grid copies (delta = 7.5, 22.5, 37.5) plus ' ...
    'their +-0.5 deg copies and the D1 grid serve all 24 headings. (iii) D3b: seas fixed here from the programme ' ...
    '(second component at 30, 60, 90 deg with 10 and 25% of the energy; one cos^2s spread, s = 10, 24 directions at ' ...
    '15 deg), every sea rotated with the primary heading over the same 24 headings; the inverse is the frozen ' ...
    'single-direction model at the primary heading (heading known, isolating the model error from D3a); Sigma, F and ' ...
    'the projection weights are those under the directional sea (what the estimator delivers, ruler directional; the ' ...
    'V2 nominal ruler is a tester cross-check); b_dir = f_W(dir) - f_W(single), d_tot from b_W + b_dir; the estimator ' ...
    'acceptance under the directional sea. Reference per condition (a processing choice): the smallest A among ' ...
    'references with d_tot <= 0.5, the smallest d_tot (least-bad diagnostic), and the precision-optimal one ' ...
    '(reported); choosing it with knowledge of the bias is optimistic, so no-feasible-layout is a robust conclusion. ' ...
    'Gate: d_tot <= 0.5 in every sea and heading; if no layout passes at some ' ...
    'n_s, that is the result, with the least-bad layout (min over layouts of max d_tot) and the per-sea counts as ' ...
    'diagnostics; the gate is never relaxed. D3b at the headline noise only (runtime; the bias is noise-free, only ' ...
    'Sigma depends on S_nn). (iv) Count rule as D1 on the worst-case optimum (min over layouts of max over headings of ' ...
    'A): a sensor is worth adding if it lowers that optimum''s worst-case sigma_lnbeta by >= 20%; recommended n_s is the ' ...
    'smallest whose worst-case optimum is Identifiable at every heading (D3a), and, with D3b, whose bias-feasible ' ...
    'WORST-CASE optimum (min over feasible layouts of max A) is Identifiable in every sea and heading; the feasible ' ...
    'mean-A optimum is the primary D3b ranking.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-05', 'field', 'D3.headingsDeg (AMENDED: 0 + 15k -> 7.5 + 15k deg)', ...
    'reason', ['AMENDMENT before any D3 production run (programme rev. 4 registered 0, 15, ..., 345 deg). Replaced by ' ...
    'the midpoint grid 7.5 + 15k deg to avoid discrete oversampling of the symmetry-axis stationary points in the ' ...
    'nuisance-heading Fisher calculation: on a grid axis a layout whose sensors all lie on that diameter (Level 2C, ' ...
    'the D1 optimum s6 + s18) has dT/dpsi = 0 by mirror symmetry, so F_psipsi = F_thetapsi = 0 and the Schur complement ' ...
    'is 0/0 at a measure-zero heading. The midpoint grid is the same 15 deg uniform quadrature without it. Heading 0 ' ...
    'is retained separately (known heading) for the D1 reproduction gate.']);
cfg.meta.changes(end + 1) = struct('date', '2026-10-08', 'field', ...
    'EMM FRF amplitude normalisation (AMENDED: computeSensorFRF H -> alpha .* H)', 'reason', ...
    ['AMENDMENT after all production runs. The Forward Model forces with Montiel''s incident potential ' ...
    '(1/(i alpha)) e^{k0 x} phi_0 and recovers eta from d_z phi = i alpha eta, so its eta is the response to an ' ...
    'incident wave of amplitude 1/alpha, not 1. computeSensorFRF treated it as per unit amplitude, so every FRF ' ...
    'was low by alpha(omega) (1.7 to 13.85 in band). Transmissibility ratios unaffected; absolute levels, SNR, ' ...
    'sigma and d affected. Detected by the long-wave check |alpha eta| -> 1 (computeSensorFRFTester group 11). ' ...
    'Fix: computeSensorFRF multiplies by alpha. twinCache migrated exactly (HaNodes .* alpha(omegaNodes), ' ...
    'per-file depth; migrateTwinCacheAlpha, validateAlphaMigration all PASS; original kept as ' ...
    'twinCache_preAlphaFix). Pre-fix vs post-fix E1 headline: Results/E1/alphaScalingCheck_20261008_170121. ' ...
    'All studies to be rerun at unchanged settings (L = 2048 baseline retained).']);

%% ---- Physics and the basin reference p0 -------------------------------------------------------
cfg.physics.g = 9.81;
cfg.physics.Hbasin = 1.88;          % m, basin depth (EMM default WaterDepth)
cfg.physics.rhoWbasin = 1000;       % kg/m^3, fresh-water basin (runFloeRegimeScreen)
cfg.physics.rhoWsea = 1025;         % kg/m^3, MIZ
cfg.physics.nuEMM = 0.30;           % Poisson ratio used for p0

cfg.p0 = struct('beta', 4.6985e-5, 'gamma', 1.4548e-3, 'R', 0.3830);
cfg.p0.vec = [cfg.p0.beta, cfg.p0.gamma, cfg.p0.R];
cfg.p0.Rphys = cfg.p0.R * cfg.physics.Hbasin;                                            % 0.720 m
cfg.p0.D = cfg.p0.beta * cfg.physics.rhoWbasin * cfg.physics.g * cfg.physics.Hbasin^4;  % 5.76 N m
cfg.p0.m = cfg.p0.gamma * cfg.physics.Hbasin * cfg.physics.rhoWbasin;                   % 2.74 kg/m^2

%% ---- Frozen estimator and forward-model settings ----------------------------------------------
cfg.acq.dt = 0.1;
cfg.acq.Nref = 65536;               % 109 min
cfg.welch = struct('L', 2048, 'overlap', 0.5, 'window', 'hann-periodic', 'binStep', 2, 'NeffRef', 59.7);
cfg.band.basin = [3.178 8.301];     % rad/s, retained band (every 2nd L = 2048 bin, 84 bins)
cfg.band.estimate = [3 8.5];        % rad/s, estimator band before bin selection
cfg.emm.truncation = [50 10 10];    % [M P N]
cfg.emm.truncationCheck = [70 15 15];
cfg.emm.alphaValidated = [1.7 13.85];
cfg.emm.nodeSpacing = 0.2;          % rad/s, solver model grid (validated at p0, A, B only)
cfg.emm.nodeSpacingCheck = 0.1;     % rad/s, record grid; A1 checks 0.2 against 0.1
cfg.emm.maxInterpBiasDistance = 0.1;
cfg.emm.jacobianStep = 1e-3;
cfg.sea = struct('Hs', 0.05, 'omegaP', 5.0, 'gammaJ', 3.3);   % G3 JONSWAP

%% ---- Sensor layouts --------------------------------------------------------------------------------
% Level 2C candidate grid (level2C_finalCheck.m): centre + r = [0.3 0.5 0.7 0.9] R x 8 angles.
% Stored as FRACTIONS of R and angles; converted to physical coordinates ONCE per scenario at the
% true R and then held fixed (never moved with a trial R during differentiation).
rFrac = [0.3 0.5 0.7 0.9];
th = (0:7) * pi / 4;
[TT, RR] = meshgrid(th, rFrac);
RR = RR.'; TT = TT.';
cfg.layout.gridFrac = [0 0; RR(:), TT(:)];         % 33 x 2 [r/R, theta], index order as level2C
cfg.layout.level2C.idx = [2 6 14 26];             % s2 s6 s14 s26
cfg.layout.level2C.frac = [0.3 0; 0.3 pi; 0.5 pi; 0.9 0];
cfg.layout.level2C.ref = 4;                       % s26 (position within the layout)

%% ---- Classification (exhaustive, applied in order) -------------------------------------------------
% s_max = max(sigma_lnbeta, sigma_lnR). Bias: the evaluator adds the bias VECTORS,
%   dtheta_tot = dtheta_W + dtheta_sys,  d_tot = sqrt(dtheta_tot' F dtheta_tot),
% so systematic errors can add or partly cancel; only the thresholds live here.
cfg.class.names = {'Identifiable', 'Marginal', 'Not identifiable'};
cfg.class.identifiable = struct('maxSigma', 0.01, 'maxBiasDistance', 0.5, 'maxCondF', 1e8);
cfg.class.marginal = struct('maxSigma', 0.05, 'maxBiasDistance', 1.0, 'maxCondF', 1e8);
cfg.class.referenceRecordN = cfg.acq.Nref;
cfg.class.toleranceLevels = struct('d', [0.5 1], 'relBeta', 0.01);   % first-crossing rule

%% ---- Noise cases (one-sided, per rad/s, vertical, basin band) --------------------------------------
names = {'datasheet', 'fused3', 'lsm6dsv16x', 'g3', 'icm42688p', 'lsm6ds3trc'};
Snn = [6.5e-8, 5.0e-7, 8.0e-7, 1.416e-6, 1.52e-6, 1.24e-5];
labels = {'Datasheet grade (65 ug/rtHz)', 'Three on-board IMUs fused', 'LSM6DSV16X', ...
    'G3 twin assumption (10% stress)', 'ICM-42688-P', 'LSM6DS3TR-C'};
cfg.noise.names = names;
cfg.noise.labels = labels;
cfg.noise.Snn = Snn;
cfg.noise.sigma = sqrt(pi * Snn / cfg.acq.dt);    % per-sample std at dt = 0.1 s
for i = 1:numel(names), cfg.noise.(names{i}) = Snn(i); end
cfg.noise.default = 'lsm6dsv16x';

%% ---- E1 validation gate targets (from U1 / L2048 / G3 result files) ----------------------------------
cfg.E1.sigmaF = [0.00462 0.00088];                % setting F at p0
cfg.E1.dPred = struct('A512', 3.68, 'B1024', 0.91, 'F2048', 0.26);
cfg.E1.sigmaTruthA = [0.00498 0.00095];
cfg.E1.sigmaTruthB = [0.00431 0.00082];
cfg.E1.tolSigma = 0.05;
cfg.E1.tolSigmaCovMC = 0.20;                      % per-element, MC standard error ~10%
cfg.E1.tolD = 0.10;                               % AMENDMENT 2026-10-01, see cfg.meta.changes
cfg.E1.truthA = [1.2 * cfg.p0.beta, cfg.p0.gamma, 0.97 * cfg.p0.R];
cfg.E1.truthB = [0.8 * cfg.p0.beta, cfg.p0.gamma, 1.03 * cfg.p0.R];

%% ---- R4: gamma uncertainty ---------------------------------------------------------------------------
cfg.R4.epsGamma = [-0.20 -0.10 -0.05 -0.02 -0.01 -0.005 0.005 0.01 0.02 0.05 0.10 0.20];
cfg.R4.nonlinearCheck = [-0.20 -0.05 0.05 0.20];
cfg.R4.noiseCases = names;                         % CLARIFICATION 2026-10-01, see cfg.meta.changes
cfg.R4.headlineNoise = 'lsm6dsv16x';               % the noise case the headline numbers and panel (a) use
cfg.R4.toleranceSearch = [-0.30 0.30];             % eps range searched for the first-crossing tolerances
cfg.R4.toleranceN = 1201;                          % points on that grid (0.05% spacing)

%% ---- D2: record duration -----------------------------------------------------------------------------
cfg.D2.durationMin = [10 20 30 60 109 180 240];
cfg.D2.L = [512 1024 2048 4096];
cfg.D2.minSegments = 8;                           % K = floor(2N/L) - 1 at 50% overlap
cfg.D2.noiseCases = names;
cfg.D2.headlineNoise = 'lsm6dsv16x';               % CLARIFICATION 2026-10-02, see cfg.meta.changes

%% ---- R3: noise-PSD mis-specification -----------------------------------------------------------------
cfg.R3.epsNoise = [-1.0 -0.5 -0.3 -0.1 0.1 0.3 0.5];   % -1 = no correction
cfg.R3.colouredCase = 'lsm6ds3trc_lowfreq_shape';       % measured spectral shape, basin level
cfg.R3.noiseCases = names;
cfg.R3.headlineNoise = 'lsm6dsv16x';               % CLARIFICATION 2026-10-02, see cfg.meta.changes
cfg.R3.toleranceSearch = [-1.0 0.5];               % eps range searched for the first-crossing tolerances
cfg.R3.toleranceN = 1501;                          % points on that grid (0.1% spacing)

%% ---- D1: sensor count and layout -----------------------------------------------------------------------
cfg.D1.sensorCounts = [2 3 4];
cfg.D1.sensorCountsStretch = [5 6];
cfg.D1.maxRadiusFrac = 0.90;                      % edge clearance as Level 2C
cfg.D1.buoyDiameter = 0.10;                       % m, PROVISIONAL (SHARC buoy not final)
cfg.D1.minSpacing = cfg.D1.buoyDiameter;          % m, centre-to-centre: two buoys cannot overlap
cfg.D1.edgeClearance = cfg.D1.buoyDiameter / 2;   % m, buoy must sit wholly on the floe
cfg.D1.minSpacingSensitivity = [0.05 0.15];       % m, reported alongside, not a second optimum
cfg.D1.optimiseReference = true;
cfg.D1.criteria = struct('primary', 'A', 'secondary', {{'D', 'E'}});
cfg.D1.noiseCases = {'lsm6dsv16x', 'icm42688p', 'g3'};
cfg.D1.reportUnconstrained = true;
cfg.D1.compareGramian = true;                     % Level 2C lambda_min optimum per n_s
cfg.D1.worthItFraction = 0.20;                    % extra sensor must cut sigma_lnbeta by >= 20%
cfg.D1.floe = 'p0';

%% ---- A1: floe-property sweep ---------------------------------------------------------------------------
% (a) parameter-space ring and corners (basin, p0 gamma, nu = 0.3)
cfg.A1.ringBetaRatio = [0.25 0.5 2 4];
cfg.A1.ringRRatio = [0.5 0.75 1.5 2];
cfg.A1.cornerRatios = [0.5 0.5; 0.5 2; 2 0.5; 2 2];         % [beta/beta0, R/R0]
param = struct('name', {}, 'group', {}, 'p', {});
for b = cfg.A1.ringBetaRatio
    param(end + 1) = struct('name', sprintf('ring_beta_x%g', b), 'group', 'ring', ...
        'p', [b * cfg.p0.beta, cfg.p0.gamma, cfg.p0.R]); %#ok<AGROW>
end
for r = cfg.A1.ringRRatio
    param(end + 1) = struct('name', sprintf('ring_R_x%g', r), 'group', 'ring', ...
        'p', [cfg.p0.beta, cfg.p0.gamma, r * cfg.p0.R]); %#ok<AGROW>
end
for c = 1:size(cfg.A1.cornerRatios, 1)
    cr = cfg.A1.cornerRatios(c, :);
    param(end + 1) = struct('name', sprintf('corner_beta_x%g_R_x%g', cr), 'group', 'corner', ...
        'p', [cr(1) * cfg.p0.beta, cfg.p0.gamma, cr(2) * cfg.p0.R]); %#ok<AGROW>
end
cfg.A1.param = param;

% (b) physical classes. Material values are nominal; flagged ones are provisional.
PP = struct('E', 1.5e9, 'nu', 0.40, 'rho', 910);   % polypropylene: SG 0.91 (builder), E typical 1.3-1.8 GPa
H = cfg.physics.Hbasin; rhoW = cfg.physics.rhoWbasin; g = cfg.physics.g;
phys = struct('name', {}, 'class', {}, 'deepWater', {}, 'Rphys', {}, 'h', {}, 'E', {}, 'nu', {}, ...
    'rhoI', {}, 'H', {}, 'rhoW', {}, 'provisional', {}, 'note', {});
phys(end + 1) = mk('basin_p0', 'basin', false, cfg.p0.Rphys, NaN, NaN, cfg.physics.nuEMM, NaN, H, rhoW, false, ...
    'EMM reference; enters via D and m, not h and E');
phys(end + 1) = mk('pp3mm_R072', 'tank', false, 0.72, 0.003, PP.E, PP.nu, PP.rho, H, rhoW, false, ...
    'p0-radius PP analogue: draught matched to p0, D 4.02 vs 5.76 N m (beta 0.70 beta0)');
phys(end + 1) = mk('pp5mm_D40', 'tank', false, 0.20, 0.005, PP.E, PP.nu, PP.rho, H, rhoW, false, ...
    'one 5 mm PP sheet, 40 cm diameter (the model floe''s core sheet)');
phys(end + 1) = mk('pp10mm_D40', 'tank', false, 0.20, 0.010, PP.E, PP.nu, PP.rho, H, rhoW, false, ...
    'two bonded 5 mm PP sheets, 40 cm diameter');
phys(end + 1) = mk('pp5mm_D100', 'tank', false, 0.50, 0.005, PP.E, PP.nu, PP.rho, H, rhoW, false, ...
    '5 mm PP sheet, 1 m diameter');
hModel = 0.04;                                     % volume-equivalent flat plate of a 6 cm lens (2/3 of max)
for Eeff = [0.5e9 1.5e9 3.0e9]
    phys(end + 1) = mk(sprintf('modelFloe_E%.1fGPa', Eeff / 1e9), 'tank', false, 0.22, hModel, Eeff, PP.nu, ...
        PP.rho, H, rhoW, true, ['SHARC model floe: 44 cm, 6 cm max (elliptical), SG 0.91, E unknown; ' ...
        'h and R provisional until CAD and weighing (Fri 2 Oct); thin-plate validity marginal']); %#ok<AGROW>
end
MIZ = struct('E', 6e9, 'nu', 0.3, 'rho', 917);
for Rm = [10 25 50]
    phys(end + 1) = mk(sprintf('miz_R%d_h1', Rm), 'miz', true, Rm, 1.0, MIZ.E, MIZ.nu, MIZ.rho, Inf, ...
        cfg.physics.rhoWsea, false, 'screening class B2; regime/domain screening unless checks pass'); %#ok<AGROW>
end
phys(end + 1) = mk('miz_R25_h05_E3', 'miz', true, 25, 0.5, 3e9, 0.3, MIZ.rho, Inf, cfg.physics.rhoWsea, false, ...
    'screening class B2; regime/domain screening unless checks pass');
for i = 1:numel(phys)
    t = toEMM(phys(i), cfg, g);
    if i == 1, physOut = t; else, physOut(i) = t; end %#ok<AGROW>
end
cfg.A1.physical = physOut;

% Band rule. The floe-relative rule (same kR range as p0) was dropped at pre-registration: for the
% 20-22 cm floes it needs omega up to ~15 rad/s, alpha ~ 40, far outside the validated EMM range.
% Finite-depth (basin/tank) cases therefore use the validated basin band itself (alpha in [1.94, 13.2]).
% A1 then answers "which floes are identifiable under the fixed, validated basin excitation band?",
% an engineering question. It does NOT isolate floe properties: changing R changes kR as well.
cfg.A1.bandRule.finiteDepth = 'basin band, same alpha window as p0';
cfg.A1.bandRule.finiteDepthBand = cfg.band.basin;
cfg.A1.bandRule.mizPeriods = [6 12.5];            % s; effective depth set at 12.5 s (screenFloeRegime)
cfg.A1.requireTruncationCheck = true;
cfg.A1.requireNodeGridCheck = true;
cfg.A1.layoutFrac = cfg.layout.level2C.frac;      % sensors placed at Level 2C fractions of each true R
cfg.A1.noiseCase = 'lsm6dsv16x';
cfg.A1.mizEvaluation = 'froude_scaled_basin_equivalent';   % AMENDMENT 2026-10-02, see cfg.meta.changes
cfg.A1.maxTruncationBiasDistance = 0.1;                    % AMENDMENT 2026-10-02; superseded as a gate, see next line
cfg.A1.truncationGate = struct('maxRelSigma', 0.01, 'maxDeltaDW', 0.02, 'sameClass', true);  % AMENDMENT 2026-10-02 (after p0 pre-flight)
cfg.A1.passNuToEMM = true;                                 % CLARIFICATION 2026-10-02
cfg.A1.modelCheckClass = 'Model check failed';             % CLARIFICATION 2026-10-02

%% ---- R1: SNR axis ---------------------------------------------------------------------------------------
cfg.R1.Snn = logspace(-8, -4, 41);
cfg.R1.sea = cfg.sea;
cfg.R1.marked = names;
cfg.R1.boundaryRule = 'all class transitions on the S_nn interval, refined on the changing criterion';   % CLARIFICATION 2026-10-03
cfg.R1.refineTolDecades = 1e-3;                     % boundary located to 0.001 decade in S_nn (0.23%)
cfg.R1.equivalentHsSensor = 'lsm6dsv16x';          % boundaries also expressed as the Hs at which this sensor reaches them

%% ---- R2: spectral shape (normalised to fixed incident variance inside the retained band) ------------
cfg.R2.omegaP = [3.5 4.25 5.0 6.0 7.5];
cfg.R2.gammaJ = [1.0 3.3 7.0];
cfg.R2.normalisation = 'fixed_inband_elevation_variance';   % isolates shape from SNR (R1 covers SNR)
cfg.R2.referenceSea = cfg.sea;                               % sets the in-band variance
cfg.R2.bimodal = struct('omegaP', [3.5 6.5], 'gammaJ', [7.0 3.3], 'energyFraction', [0.4 0.6]);
cfg.R2.noiseCase = 'lsm6dsv16x';
cfg.R2.checkL = [1024 2048 4096];
cfg.R2.normalisationBand = cfg.band.basin;                  % CLARIFICATION 2026-10-03: the retained estimator band
cfg.R2.bimodalFractionOf = 'retained-band elevation variance';
cfg.R2.adequacyRule = 'Identifiable at L = 2048';
cfg.R2.m1Candidates = 'gamma_J = 7 unimodal seas and the bimodal sea';
cfg.R2.m1Rule = 'largest max(s_max / 0.01, d_W / 0.5, kappa / 1e8) at L = 2048';

%% ---- V1: forward-model mismatch -------------------------------------------------------------------------
cfg.V1.truncationTruth = [130 20 20];                        % SELECTED 2026-10-04 by stage 0 (see cfg.meta.changes)
%   ([70 15 15] was rejected: feature d 70 -> 90 = 0.25 > 0.1, diagnoseTruncationP0 2 Oct)
cfg.V1.truncationInverse = cfg.emm.truncation;
% stage 0 ladder (CLARIFICATION 2026-10-04, see cfg.meta.changes): extend M only, P and N fixed
cfg.V1.truncationLadderM = [90 110 130 150 170 190 210];   % [90 20 20] is the A1 diagnostic's last level
cfg.V1.truncationLadderPN = [20 20];
cfg.V1.truncationConvergedD = 0.1;                          % first consecutive step with d below this
cfg.V1.truncationFloes = {'ring_R_x2', 'corner_beta_x0.5_R_x2', 'corner_beta_x2_R_x2'};   % large-kR (diagnostic)
cfg.V1.truncationCheckP = 30;                               % P check at the selected M (diagnostic)
cfg.V1.truncationTruthSelected = true;    % stage 0 run truncationLadder_20261004_113129 (logged)
% V1 study (CLARIFICATION 2026-10-04, see cfg.meta.changes)
cfg.V1.radialErrorAppliesTo = 'every sensor with r > 0, common signed shift, angles unchanged';
cfg.V1.depthModel = 'physical: floe, sensor positions and physical-frequency sea fixed; band and taper at the nominal physical band';
cfg.V1.toleranceThresholds = struct('dSys', [0.5 1], 'betaPct', 1);
cfg.V1.toleranceTolDecades = 0.005;      % PRE-RUN CORRECTION 2026-10-04: bisection in log10 |error| (1.2% relative)
cfg.V1.toleranceFloorFraction = 1e-4;     % lower bracket when the crossing lies between 0 and the first registered point
cfg.V1.nonlinear = struct('rule', 'largest analytic d_sys over all registered V1 cases', 'start', 'theta_true', ...
    'solver', struct('hStep', 1e-3, 'maxIt', 20, 'stepSigma', 3, 'tolSigma', 0.01), 'referenceGapSigma', 0.2);
cfg.V1.depthErrorFrac = [-0.05 -0.02 0.02 0.05];
cfg.V1.sensorRadialError = [-0.02 -0.01 0.01 0.02];       % m (divide by H for the EMM)

%% ---- V2: directional forcing ----------------------------------------------------------------------------
cfg.V2.angleDeg = [15 30 60 90];
cfg.V2.secondEnergyFraction = [0.05 0.10 0.25 0.50];
cfg.V2.coherenceDiagnostic = true;
% clarification logged 2026-10-05 before any V2 result (see cfg.meta.changes; nothing above changed)
cfg.V2.primaryHeadingDeg = 0;                    % the EMM incidence (+x): the Level 2C / D1 axis
cfg.V2.energyConvention = 'fixedTotal';          % S_u1 = (1 - f2) S_u, S_u2 = f2 S_u, same JONSWAP shape
cfg.V2.operatingPoint = 'p0, Level 2C, reference s26, LSM6DSV16X, setting F, [50 10 10] (E1 default)';
cfg.V2.thresholds = struct('dSys', [0.5 1], 'betaPct', 1);
cfg.V2.toleranceTolDecades = 0.005;              % bisection in log10 f2, as V1
cfg.V2.toleranceFloorFraction = 1e-4;            % lower bracket from 0: this fraction of the first registered f2
cfg.V2.coherence = struct('statistic', 'fisherZ', 'alpha', 0.05, 'power', 0.80, 'perBinOneSided', 0.95, ...
    'nullRecords', 400, 'nullSeedBase', 800000, 'nullRecordsTest', 100);   % null MC: AMENDED 2026-10-05, before any run
cfg.V2.linearityF2 = [2.5e-4 5e-4 1e-3];         % small-f2 local-regime check (d_sys / f2 constant), AMENDED idem
cfg.V2.mirrorCheckDeg = 30;                      % tester: +phi and -phi give the same S at Level 2C (on-axis layout)
cfg.V2.nonlinear = struct('rule', 'd_sys = 1 crossing of the most sensitive angle; else registered case nearest 1', ...
    'start', 'theta_true', 'solver', cfg.V1.nonlinear.solver, 'referenceGapSigma', 0.2);
cfg.V2.requireCleanTree = true;

%% ---- D3: direction-robust sensor count and layout (programme rev. 4; clarified 2026-10-05 before any run) ----
cfg.D3.sensorCounts = cfg.D1.sensorCounts;       % exhaustive n_s = 2, 3, 4, reference optimised per condition
cfg.D3.minSpacing = cfg.D1.minSpacing;           % D1 admissibility (radius, edge, spacing)
cfg.D3.noiseCases = cfg.D1.noiseCases;           % D3a: all three; headline first
cfg.D3.headingsDeg = 7.5 + 15 * (0:23);          % AMENDED 2026-10-05 pre-run: midpoint grid (registered 0:15:345)
cfg.D3.headingStepDeg = 0.5;                     % d T / d psi by central differences in the rotation (+-0.5 deg)
cfg.D3.headingStepCheckDeg = 0.25;               % tester: halved step
cfg.D3.d3b = struct('kind', {'two', 'two', 'two', 'two', 'two', 'two', 'spread'}, ...
    'phiDeg', {30, 30, 60, 60, 90, 90, NaN}, 'f2', {0.10, 0.25, 0.10, 0.25, 0.10, 0.25, NaN}, ...
    's', {NaN, NaN, NaN, NaN, NaN, NaN, 10}, 'nDir', {NaN, NaN, NaN, NaN, NaN, NaN, 24});
cfg.D3.d3bNoise = cfg.noise.default;             % CLARIFIED: D3b at the headline noise only
cfg.D3.d3bRuler = 'directional';                 % CLARIFIED: Sigma, F, weights and d_tot under the directional sea
cfg.D3.biasGate = 0.5;                           % d_tot <= 0.5 in every D3b case (sea x heading)
cfg.D3.worthItFraction = cfg.D1.worthItFraction; % 20% rule on the WORST-CASE sigma_lnbeta of the worst-case optimum
cfg.D3.d1Gate = struct('layout', [6 18], 'ref', 18);   % heading 0, known: the n_s = 2 optimum must be D1's (= cfg.M1.D1)
cfg.D3.requireCleanTree = true;

%% ---- M1: selection RULES (scenarios resolved after D1, A1, R2) ------------------------------------------
cfg.M1.nRecords = 100;
cfg.M1.nRecordsExtended = 200;
cfg.M1.rules = {'D1 optimum at n_s = 2 (s6, reference s18)', 'A1 case nearest the Identifiable/Marginal boundary', ...
    'R2 case by cfg.R2.m1Rule', 'p0 at LSM6DSV16X noise'};   % rules 1 and 3 AMENDED 2026-10-03
cfg.M1.nonlinearBetaOffsets = [-0.20 0.20];
cfg.M1.accept = struct('empPred', [0.85 1.20], 'coverage95', [0.88 0.99], 'nonlinVsLinSigma', 0.2);
% resolved cases and run settings (CLARIFICATION 2026-10-03, see cfg.meta.changes; nothing above changed)
cfg.M1.caseNames = {'D1_ns2', 'A1_miz_R25_h1', 'R2_wp3.5_gJ7', 'R1_p0_lsm6dsv16x'};
cfg.M1.D1 = struct('ns', 2, 'layout', [6 18], 'ref', 18, 'noiseCase', 'lsm6dsv16x', 'spacingIndex', 1);
cfg.M1.A1scenario = 'miz_R25_h1';
cfg.M1.R2sea = 'wp3.5_gJ7';
cfg.M1.R1noiseCase = 'lsm6dsv16x';
cfg.M1.seedBase = 700000;                        % seed = seedBase + seedStride * caseIndex + record
cfg.M1.seedStride = 10000;
cfg.M1.nonlinearRecord = 1;                      % the record inverted nonlinearly (from both starts)
cfg.M1.solver = struct('hStep', 1e-3, 'maxIt', 20, 'stepSigma', 3, 'tolSigma', 0.01);   % = G3
cfg.M1.sigmaSource = 'analytic';                 % J, Sigma_k, F from evaluateScenario (E1), not Monte Carlo
cfg.M1.borderline = struct('nSE', 1, 'coverageVarianceFloor', 0.95 * 0.05);
cfg.M1.checkpointEvery = 10;                     % records between checkpoint saves
cfg.M1.sourceRelTol = 1e-6;                      % analytic target vs the source study
cfg.M1.requireCleanTree = true;                  % refuse to run with uncommitted .m files

%% ---- H1: calibration and co-located transmissibility (hardware) ---------------------------------------
cfg.H1.gLocal = 9.796;                            % m/s^2, Cape Town
cfg.H1.holdTrim = 10;                             % s trimmed from each end of a static hold
cfg.H1.accept = struct('relGain', 0.0042, 'delay', 0.37e-3, 'refNoiseRatio', 1e-3);
end

%% ================================================================================================
function s = mk(name, cls, deep, Rphys, h, E, nu, rhoI, H, rhoW, prov, note)
s = struct('name', name, 'class', cls, 'deepWater', deep, 'Rphys', Rphys, 'h', h, 'E', E, 'nu', nu, ...
    'rhoI', rhoI, 'H', H, 'rhoW', rhoW, 'provisional', prov, 'note', note);
end

function s = toEMM(s, cfg, g)
% Physical -> EMM scaling for finite depth (screenFloeRegime.m formulas). Deep water: NaN here,
% computed with screenFloeRegime in the study script (needs the dispersion relation).
if strcmp(s.name, 'basin_p0')
    s.D = cfg.p0.D; s.m = cfg.p0.m;
else
    s.D = s.E * s.h^3 / (12 * (1 - s.nu^2));
    s.m = s.rhoI * s.h;
end
s.draught = s.m / s.rhoW;
s.lf = (s.D / (s.rhoW * g))^(1/4);
s.RoverLf = s.Rphys / s.lf;
if s.deepWater
    s.p = [NaN NaN NaN];
else
    s.p = [s.D / (s.rhoW * g * s.H^4), s.draught / s.H, s.Rphys / s.H];
end
end